name: validation
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Validate
        run: |
          cd .github/workflows
          pip3 install PyGithub
          python3 test.py
