name: validation
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Validate
        run: |
          cd .github
          pip3 install PyGithub
          python3 test.py
